---
dist: bionic
language: python
# configure python version (see https://docs.travis-ci.com/user/languages/python/#specifying-python-versions)
python:
  - "3.8"

env:
  - VAGRANT_DEFAULT_PROVIDER=libvirt

services:
  - docker

# Cache the big Vagrant boxes
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
    - /home/travis/.cache/pipenv

install:
  # Install Python 3 for usage together with sudo into our Travis build image
  - sudo apt-get install python3.8
  - curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3.8

  # Install required (and locked) dependecies with pipenv
  - sudo -H pip3 install pipenv
  - sudo -H pipenv install


jobs:
  include:
    - script:
        - sudo -E pipenv run molecule test

      name: "Molecule testing Travis-locally with Docker Ubuntu Bionic 18.04"

    - script:
        - sudo -E pipenv run molecule test --scenario-name docker-ubuntu-focal

      name: "Molecule testing Travis-locally with Docker Ubuntu Focal 20.04"

    - script:
        - sudo -E pipenv run molecule test --scenario-name docker-ubuntu-xenial

      name: "Molecule testing Travis-locally with Docker Ubuntu Xenial 16.04"

    - script:
        ### Vagrant installation
        # Install libvrt & KVM (see https://github.com/alvistack/ansible-role-virtualbox/blob/master/.travis.yml)
        - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev

        # Download Vagrant & Install Vagrant package
        - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.10/vagrant_2.2.10_x86_64.deb
        - sudo dpkg -i vagrant_2.2.10_x86_64.deb
        - sudo vagrant --version

        # Install vagrant-libvirt Vagrant plugin
        - sudo vagrant plugin install vagrant-libvirt
        - sudo vagrant plugin list

        - sudo -E pipenv run molecule create --scenario-name vagrant-ubuntu
        - sudo -E pipenv run molecule converge --scenario-name vagrant-ubuntu
        - sudo -E pipenv run molecule verify --scenario-name vagrant-ubuntu
        - sudo -E pipenv run molecule destroy --scenario-name vagrant-ubuntu

      name: "Molecule testing Travis-locally with Vagrant Ubuntu Bionic 18.04"


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/