---
scenario:
  name: vagrant-libvirt-ubuntu

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: vagrant-libvirt-ubuntu
    box: generic/ubuntu1804
    memory: 512
    cpus: 1
    provider_raw_config_args:
      - 'nic_model_type = "virtio"'
      - 'disk_bus = "virtio"'
      - 'volume_cache = "none"'
      - 'storage :file, bus: "virtio", cache: "none"'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
  playbooks:
    converge: ../playbook.yml

lint:
  name: yamllint
  enabled: false
verifier:
  name: testinfra
  directory: ../tests/
  env:
    # get rid of the DeprecationWarning messages of third-party libs,
    # see https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 1
