name: molecule

on: [push]

jobs:
  molecule-vagrant-ubuntu:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install required (and locked) dependecies with pipenv
      run: |
        echo "Install required (and locked) dependecies with pipenv"
        pip install pipenv
        pipenv install

    - name: Molecule testing GHA-locally with Vagrant Ubuntu Bionic 18.04
      run: |
        pipenv run molecule create --scenario-name vagrant-ubuntu
        pipenv run molecule converge --scenario-name vagrant-ubuntu
        pipenv run molecule verify --scenario-name vagrant-ubuntu
        pipenv run molecule destroy --scenario-name vagrant-ubuntu
